name: prime_numbers
description: This package is to help anyone on their prime number adventures and
  provide tools to ease working with prime numbers.
version: 0.0.2
homepage: https://github.com/guidotheelen/prime_numbers

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
